version: '3.8'

services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    external: true
